name: DAST Scan
on: push

jobs:

  zap_scan:
    runs-on: ubuntu-latest
    name: Run DAST scan on the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://192.168.8.115:3000/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          artifact_name: zap_scan
